#!/bin/sh
cp splash_files/Runway-Boot-Image.png  binary/isolinux/buttonos.lss
cp splash_files/Runway-Boot-Image.png binary/isolinux/splash.png
cp splash_files/Runway-Boot-Image.png binary/syslinux/splash.png && exit 0
