#!/bin/sh

#MIRROR_DEBIAN="ftp://mirror.hetzner.de/ftp.de.debian.org/debian/"
MIRROR_DEBIAN="http://localhost:3142/ftp.debian.org/debian"

lb config noauto --clean \
	--apt-recommends false \
	--bootappend-live "homepage=http://portal.webconverger.com nonetworking nopersistent quickreboot nomodeset noroot splash" \
	--cache-stages "bootstrap rootfs" \
	-k 486 \
	-a i386 \
	-f standard \
	-b iso-hybrid \
	--apt apt \
	--username webc \
	--hostname webconverger \
	--bootloader syslinux \
	--archive-areas "main contrib non-free" \
	--distribution sid \
	--iso-publisher "Webconverger; http://webconverger.com/; support@webconverger.com" \
	--iso-volume "Webconverger $(date +%Y%m%d-%H:%M)" \
	--memtest none \
	-m ${MIRROR_DEBIAN} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--win32-loader false \
	--source false \
	-r 'unofficial.debian-maintainers.org live.debian.net' \
	${@}
