#!/bin/sh

#MIRROR_DEBIAN="ftp://mirror.hetzner.de/ftp.de.debian.org/debian/"
MIRROR_DEBIAN="http://ftp.us.debian.org/debian"

lb config noauto --clean \
	--apt-recommends false \
	--bootappend-live "quiet splash homepage=http://www.commonde.org/start nonetworking video=vesa:ywrap,mtrr vga=792 nopersistent quickreboot noroot" \
	--cache-stages "bootstrap rootfs" \
	-k 486 \
	-a i386 \
	-f standard \
	-b iso-hybrid \
	--apt apt \
	--username webc \
	--hostname commonde \
	--bootloader syslinux \
	--archive-areas "main contrib non-free" \
	--distribution squeeze \
	--iso-publisher "commonde; http://commonde.org/; support@commonde.org" \
	--iso-volume "CommonDE $(date +%Y%m%d-%H:%M)" \
	--memtest none \
	--syslinux-splash config/binary_syslinux/splash.rle \
	--syslinux-timeout 1 \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--binary-indices false \
	--win32-loader false \
	--source false \
	-r 'unofficial.debian-maintainers.org live.debian.net' \
	${@}
